// src/components/Info.jsx
import pfp from '@/images/pfp2.jpeg';

export default function Info({ reference }) {
    const diff = new Date() - new Date("2006-03-13");
    const age = Math.floor(diff / 31536000000);

    / * 3.5 rem is navbar height * /

    return (
        <div className="h-screen bg-gray-900" ref={reference} style={{ scrollMargin: "3.5rem" }}>
            <div className="flex justify-center items-center flex-col gap-4 h-full">
                <img src={pfp} alt="pfp" className="rounded-md h-1/3 mt-2" />
                <div className="text-center flex items-center gap-2">
                    <h1 className="text-4xl text-white">Hi,</h1>
                    <p className="text-4xl text-gray-400">
                        I'm{' '}
                        <span className="text-blue-700">
                            Luc Francis
                        </span>
                    </p>
                </div>
                <p className="text-lg text-white max-w-screen-md pl-4 pr-4">
                    I'm a {age}-year old frontend web developer most proficient in React.
                    I've been programming in JavaScript since the age of 10, and
                    have created many passion projects since then. I
                    am always looking to improve as a developer, and I am constantly
                    picking up new frameworks and technologies.
                </p>
            </div>
        </div>
    )
}

// src/components/Info.svelte
<script>
// @ts-nocheck

    import pfp from "../images/pfp.jpg";
    import DiGithubBadge from "svelte-icons/di/DiGithubBadge.svelte";
    import FaLinkedin from "svelte-icons/fa/FaLinkedin.svelte";

    const diff = new Date() - new Date("2006-03-13");
    const age = Math.floor(diff / 31536000000);
</script>

<div class="flex">
    <div style="text-align: left;">
        <h1 style="font-size: 2.5rem; margin: 0px;">Hi, I'm</h1>
        <h1 class="name">Luc Francis</h1>
        <p id="bio">
            I'm a {age} year old frontend web developer most proficient in React. I
            am always looking to improve as a developer, and I am constantly
            picking up new frameworks and technologies.
        </p>
        <div class="socials-container">
            <a href="https://github.com/luca1s" class="icon">
                <DiGithubBadge />
            </a>
            <a href="https://www.linkedin.com/in/luca1s/" class="icon">
                <FaLinkedin />
            </a>
        </div>
    </div>
    <img src={pfp} style="max-width: 25vw;" alt="profile" />
</div>

<style>
    .name {
        font-size: 4rem;
        margin: 0px;
        left: 0;
        color: #4287f5;
    }

    @media (max-width: 768px) {
        .name {
            font-size: 2.5rem;
        }
    }

    .flex {
        display: flex;
        align-items: center;
        justify-content: center;
        gap: 2rem;
        margin-left: 1rem;
        margin-right: 1rem;
    }

    .flex img {
        border-radius: 14px;
    }

    #bio {
        max-width: 50em;
        margin: auto;
    }

    .icon {
        color: white;
        width: 3em;
        height: 3em;
    }

    .icon:hover {
        color: red;
    }

    .socials-container {
        margin-top: 1rem;
        display: flex;
        align-items: center;
        justify-content: left;
    }
</style>
